<div class="table-responsive">
        <table class="table table-striped mb-0" id="datatable">
            <thead>
                <tr>
                    <th class="align-middle text-center">#</th>
                    <th class="align-middle text-center">Total Letters</th>
                    <th class="align-middle text-center">Generated By</th>
                    <th class="align-middle text-center">Download</th>
                    <th class="align-middle text-center">Generated At</th>
                </tr>
            </thead>
            <tbody>
                <?php $__currentLoopData = $letter_download_data; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $key=>$value): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
                    <tr>
                        <td class="text-center"><?php echo e($key+1); ?></td>
                        <td class="text-center"><?php echo e($value['total_count']); ?></td>
                        <td class="text-center"><?php echo e($value['created_by']); ?></td>
                        <td class="text-center"><a href="<?php echo e(url('/admin/EditCommunication/download/'.$value['id'])); ?>"><i class="fa fa-download  text-success"></i></a></td>
                        <td class="text-center"><?php echo e($value['created_at']); ?></td>
                    </tr>
                <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
            </tbody>
        </table>
    </div><?php /**PATH D:\vipuljadav\www\projects\laravel\MagnetHCS\app/Modules/EditCommunication/Views/letter_log.blade.php ENDPATH**/ ?>