
    <div class="card shadow">
        <div class="card-header">Custom Communication</div>
        <div class="card-body">
            <ul class="nav nav-tabs" id="myTab2" role="tablist">
                <li class="nav-item"><a class="nav-link active" id="active-screen-tab" data-toggle="tab" href="#active-screen" role="tab" aria-controls="active-screen" aria-selected="true">Letter</a></li>
                <li class="nav-item"><a class="nav-link" id="active-screen-log-tab" data-toggle="tab" href="#active-screen-log" role="tab" aria-controls="active-screen-log" aria-selected="true">Letter Log</a></li>
                <li class="nav-item"><a class="nav-link" id="active1-screen-tab" data-toggle="tab" href="#active1-screen" role="tab" aria-controls="active1-screen" aria-selected="true">Email</a></li>
                <li class="nav-item"><a class="nav-link" id="active-email-tab" data-toggle="tab" href="#active-email" role="tab" aria-controls="active-email" aria-selected="true">Email Log</a></li>
            </ul>

            <div class="tab-content bordered" id="myTab2Content">
                <div class="tab-pane fade show active" id="active-screen" role="tabpanel" aria-labelledby="active-screen-tab">
                    <form class="form" id="submission_comment_form" method="post" action="{{url('admin/CustomCommunication/individual')}}" onsubmit="return validateCustomLetter()">
                    {{csrf_field()}}
                    <input type="hidden" name="id" value="{{$submission->id}}">
                        <div class="form-group">
                            <label style="width: 100%">Letter Body : <input type="submit" class="btn btn-success" name="preview" style="float: right !important;" value="Preview"></label>
                            
                            <div class="editor-height-210">
                                <textarea class="form-control" id="letter_body" name="letter_body">{{ $submission->letter_body }}
                                
                                </textarea>
                            </div>
                        </div>
                        <div class="form-group"><input type="submit" class="btn btn-secondary" value="Save Changes" name="save"> <input type="submit" name="generate_letter_now" class="btn btn-success"  value="Generate Letters Now"> 
                        </div>
                    </form>

                    


                </div>

                <div class="tab-pane fade" id="active-screen-log" role="tabpanel" aria-labelledby="active-screen-log-tab">
                    @php $custom_data = fetch_individual_custom_communication($submission->id) @endphp
                    @if(!empty($custom_data))
                        <table class="table table-striped" id="custom_details">
                          <thead>
                            <tr>
                                <th class="align-middle text-center">#</th>
                                <th class="align-middle text-center">Generated By</th>
                                <th class="align-middle text-center">Download</th>
                                <th class="align-middle text-center">Generated At</th>
                            </tr>
                          </thead>
                          <tbody>
                            @foreach($custom_data as $ckey=>$cinfo)
                                <tr>
                                    <td class="text-center">{{$ckey+1}}</td>
                                    <td class="text-center">{{getUserName($cinfo['generated_by'])}}</td>
                                    <td class="text-center"><a href="{{url('/admin/CustomCommunication/download/'.$cinfo['id'])}}"><i class="fa fa-download  text-success"></i></a></td>
                                    <td class="text-center">{{getDateTimeFormat($cinfo['created_at'])}}</td>
                                </tr>
                            @endforeach
                            
                          </tbody>
                        </table>
                    @else
                            <div class="text-center">No Data found.</div>
                    @endif
                </div>
                
                <div class="tab-pane fade" id="active1-screen" role="tabpanel" aria-labelledby="active1-screen-tab">
                    <form class="form" id="submission_comment_form" method="post" action="{{url('admin/CustomCommunication/individual/email')}}" onsubmit="return validateCustomEmail()">
                    {{csrf_field()}}
                    <input type="hidden" name="id" value="{{$submission->id}}">

                     <div class="form-group">
                        <label style="width: 100%">Mail Subject : <input type="submit" class="btn btn-success" name="preview" style="float: right !important;" value="Preview"></label>
                        <div class="">
                            <input type="text" class="form-control" name="mail_subject" id="mail_subject" value="{{$submission->email_subject}}">
                        </div>
                    </div>
                    <div class="form-group">
                        <label>Mail Body : </label>
                        <div class="editor-height-210">
                            <textarea class="form-control" id="mail_body" name="mail_body">{{$submission->email_body}}
                           
                            </textarea>
                        </div>
                    </div>
                    <div class="form-group"><input type="submit" class="btn btn-secondary" value="Save Changes" name="save"> <input type="submit" onclick="validateCustomEmail()" class="btn btn-success"  value="Send Emails Now"></div>

                </form>


                </div>

                <div class="tab-pane fade" id="active-email" role="tabpanel" aria-labelledby="active-email-tab">
                   @php $custom_data = fetch_individual_email_log($submission->id) @endphp
                    @if(!empty($custom_data))
                        <table class="table table-striped" id="custom_details">
                          <thead>
                            <tr>
                                <th class="align-middle text-center">#</th>
                                <th class="align-middle text-center">Sent By</th>
                                <th class="align-middle text-center">Email</th>
                                <th class="align-middle text-center">Sent On</th>
                                <th class="align-middle text-center">View</th>
                            </tr>
                          </thead>
                          <tbody>
                            @foreach($custom_data as $ckey=>$cinfo)
                                <tr>
                                    <td class="text-center">{{$ckey+1}}</td>
                                    <td class="text-center">{{getUserName($cinfo['generated_by'])}}</td>
                                    <td class="text-center">{{$cinfo['email']}}</td>
                                    <td class="text-center">{{getDateTimeFormat($cinfo['created_at'])}}</td>
                                    <td class="text-center"><a href="{{url('/admin/CustomCommunication/email/individual/'.$cinfo['id'])}}" target="_blank"> <i class="font-18 far fa-eye"></i> </a>
                                    </td>

                                </tr>
                            @endforeach
                            
                          </tbody>
                        </table>
                    @else
                            <div class="text-center">No Data found.</div>
                    @endif

                </div>
            </div>


          
        </div>
    </div>
</form>