<div class="table-responsive">
        <table class="table table-striped mb-0" id="datatable">
            <thead>
                <tr>
                    <th class="align-middle text-center">#</th>
                    <th class="align-middle text-center">Total Emails</th>
                    <th class="align-middle text-center">Generated By</th>
                    <th class="align-middle text-center">Download</th>
                    <th class="align-middle text-center">Generated At</th>
                </tr>
            </thead>
            <tbody>
                @foreach($mail_download_data as $key=>$value)
                    <tr>
                        <td class="text-center">{{$key+1}}</td>
                        <td class="text-center">{{$value['total_count']}}</td>
                        <td class="text-center">{{$value['created_by']}}</td>
                        <td class="text-center"><a href="{{url('/admin/LateSubmission/EditCommunication/download/'.$value['id'])}}"><i class="fa fa-download  text-success"></i></a></td>
                        <td class="text-center">{{$value['created_at']}}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>